name: Build
on: 
  push:
  pull_request:
    types: [opened]
jobs:
  test:
    name: Run tests, race detection, lint and coverage
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name:  Get dependencies
      env: 
        GOPRIVATE: github.com/genisyscu/*
        TOKEN: ${{ secrets.PAT_Checkout_Private_Repository }}
      run: |
        git config --global url."https://gcu:${TOKEN}@github.com".insteadOf "https://github.com"
        go get -v -t -d ./...

    - name: Run tests with coverage
      run: go test -v -cover ./...

    - name: Run race detection
      run: go test -v -race ./...

    - name: Install golangci-lint
      run: |
        echo ::add-path::$(go env GOPATH)/bin
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

    - name: Run golangci-lint
      run: |
        golangci-lint --version
        golangci-lint linters
        golangci-lint run ./...
