name: Build
on:
  push:
  pull_request:
    types: [opened]
jobs:
  test:
    name: Run tests, race detection, lint and coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run tests with coverage
        run: go test -v -cover ./...

      - name: Run race detection
        run: go test -v -race ./...
  golangci:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        env:
          GOPRIVATE: github.com/genisyscu/*
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.27

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
